version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 